# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ronzoni e Salsi
email: admin@ronzoniesalsi.it
description: > # this means to ignore newlines until "baseurl:"
    Impianti elettrici, fibra ottica e fotovoltaico.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ronzoniesalsi.it" # the base hostname & protocol for your site
github_username: ronzoniesalsi 

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap
